version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  # NOTE: Currently using dapr redis.
  # redis-stack:
  #   image: redis/redis-stack:latest
  #   container_name: redis-stack
  #   ports:
  #     - "6379:6379" # Redis
  #     - "8001:8001" # Redis Stack UI
  #   volumes:
  #     - redis_data:/data
  #   networks:
  #     - app-network

volumes:
  mongo_data:
  redis_data:

networks:
  app-network:
    driver: bridge
